from pydantic import BaseModel, Field


class StrategicIssue(BaseModel):
    """Specific strategic vulnerability or transformation opportunity."""

    domain: str = Field(..., description="Target business area (e.g. Sales Efficiency, HR Retention, Customer Churn)")
    issue_description: str = Field(..., description="Detailed description of the identified issue")
    root_cause: str = Field(..., description="Root cause grounded in evidence package")


class StrategicResponse(BaseModel):
    """Evidence-grounded strategic transformation plan generated by the Groq LLM reasoning engine."""

    strategic_issues: list[str] = Field(..., description="List of identified core operational/strategic issues")
    evidence: list[str] = Field(..., description="Exact citations mapping back to items in the Evidence Package")
    business_impact: str = Field(..., description="Financial, operational, or strategic risk impact")
    recommendation: str = Field(..., description="Phased action plan and strategic transformation recommendation")
    priority: str = Field(..., description="Priority level (e.g. High (Immediate Quick-Win), Medium, Long-term)")
    expected_outcome: str = Field(..., description="Projected ROI, performance gain, or cost reduction")
