from pydantic import BaseModel, Field


class StrategicIssue(BaseModel):
    """Specific strategic vulnerability or transformation opportunity."""

    domain: str = Field(..., description="Target business area (e.g. Sales Efficiency, HR Retention, Customer Churn)")
    issue_description: str = Field(..., description="Detailed description of the identified issue")
    root_cause: str = Field(..., description="Root cause grounded in evidence package")


class StrategicResponse(BaseModel):
    """Evidence-grounded strategic response generated by the reasoning engine."""

    answer: str = Field(default="", description="Direct factual natural language answer to the user query")
    strategic_issues: list[str] = Field(default_factory=list, description="List of identified core operational/strategic issues")
    evidence: list[str] = Field(default_factory=list, description="Exact citations mapping back to items in the Evidence Package")
    business_impact: str = Field(default="", description="Financial, operational, or strategic risk impact")
    recommendation: str = Field(default="", description="Actionable recommendation step (empty string if nothing meaningful to recommend)")
    priority: str = Field(default="Medium", description="Priority level (e.g. High, Medium, Notice)")
    expected_outcome: str = Field(default="", description="Projected ROI, performance gain, or outcome")
